backend:
  name: git-gateway
  branch: main

media_folder: "src/static/img"
public_folder: "/static/img"
local_backend: true

# Ustawienia
collections:
  - label: "Ustawienia"
    name: "settings"
    folder: "src/settings"
    create: false
    editor:
      preview: false
    fields:
      - { label: "Logo", name: "site_logo", widget: "image" }
      - { label: "Numer telefonu", name: "site_phone", widget: "image" }
      - { label: "Adres email", name: "site_mail", widget: "image" }
# Cennik
  - label: "Cennik" 
    name: "cennik"
    folder: "src/cennik" 
    create: true 
    slug: "{{slug}}"
    editor:
      preview: false
    fields:
      - { label: "Tytuł", name: "title", widget: "string" }
      - { label: "Typ trasy", name: "category", widget: "string" }
      - { label: "Czas spływu", name: "rafting_time", widget: "string" }
      - { label: "Długość trasy", name: "route_length", widget: "string" }
      - { label: "Cena", name: "price", widget: "string" }